config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    devise_scope :user do
      authenticated :user do
        root :to => "categories#index", as: :authenticated_root
        get '/users/sign_out' => 'devise/sessions#destroy'
      end
      unauthenticated :user do
        root :to => "splashs#index", as: :unauthenticated_root
      end
    end

    resources :categories, only: [:index, :show, :new, :create]
    resources :deals, only: [:index, :show, :new, :create]
end

app/views/shared/_card1.html.erb
<div class="card-text">
  <p><%= type1 %></p>
  <p><%= type3 %><%= type2 %></p>
</div>

app/views/shared/_card2.html.erb
<%= link_to category_path(category)  do %>
  <div class="card-1 card-2">
    <div>
      <div>
        <%= image_tag category.icon %>
      </div>
      <div>
        <p><%= category.name %></p>
        <small><%= category.created_at %></small>
      </div>
    </div>
    <div>
      <p>$<%= Deal.sum_amounts(category.deals)%></p>
    </div>
  </div>
<% end %>

app/views/shared/_card3.html.erb
<%= link_to deal_path(deal)  do %>
  <div class="card-1 card-2">
    <div>
      <div>
        <%= image_tag deal.category.icon %>
      </div>
      <div>
        <p><%= deal.name %></p>
        <small><%= deal.created_at %></small>
      </div>
    </div>
    <div>
      <p>$<%= deal.amount %></p>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
  <div class="flash-msg alert">
    <%= msg %>
  </div>
  <% else %>
  <div class="flash-msg">
    <%= msg %>
  </div>
  <% end %>

<% end %>

app/views/shared/_header.html.erb
<header>
  <div>
    <%= link_to image_tag(image1), unauthenticated_root_path %>
    <%= link_to image_tag(image3), authenticated_root_path %>
  </div>
  <div>
    <span><%= title %></span>
  </div>
  <div>
    <%= image_tag(image2) %>
  </div>
</header>

app/views/shared/_mobile_menu.html.erb
<div class="menu">
  <nav class="menu__nav">
    <div class='profile'>
      <div>
        <%= image_tag 'https://i.guim.co.uk/img/media/ef8492feb3715ed4de705727d9f513c168a8b196/37_0_1125_675/master/1125.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=d456a2af571d980d8b2985472c262b31' %>
      </div>
      <p><%= user.full_name %></p>
    </div>
    <ul class="menu__list r-list">
      <li class="menu__group">
        <%= link_to 'Home', authenticated_root_path, class: "menu__link r-link"%>
      </li>
      <li class="menu__group">
        <%= link_to 'Transactions', deals_path, class: "menu__link r-link"%>
      </li>
      <li class="menu__group">
        <%= link_to 'Categories', authenticated_root_path, class: "menu__link r-link"%>
      </li>
      </li>
    </ul>
    <div class="profile profile-link">
    <%= link_to 'Sign Out', destroy_user_session_path , method: :delete %>
    </div>
  </nav>
  <button class="menu__toggle r-button" type="button">
    <span class="menu__hamburger m-hamburger">
      <span class="m-hamburger__label">
        <span class="menu__toggle-hint screen-reader">Open menu</span>
      </span>
    </span>
  </button>
</div>


<script>
(function(){
  'use strict';

  class Menu {
    constructor(settings) {
      this.menuRootNode = settings.menuRootNode;
      this.isOpened = false;
    }
    
    changeMenuState(menuState) {
      return this.isOpened = !menuState;
    }
    
    changeToggleHint(toggleHint, toggleNode) {
      toggleNode.textContent = toggleHint;
      return toggleHint; 
    }
  }

  const menuClassesNames = {
    rootClass: 'menu',
    activeClass: 'menu_activated',
    toggleClass: 'menu__toggle',
    toggleHintClass: 'menu__toggle-hint'
  }
  
  const jsMenuNode = document.querySelector(`.${menuClassesNames.rootClass}`);
  const demoMenu = new Menu ({
    menuRootNode: jsMenuNode
  });
  
  function getCurrentToggleHint(currentMenuState) {
    return (currentMenuState !== true) ? 'Open menu' : 'Close menu';
  }
  
  function toggleMenu(event) {
    
      let currentMenuState = demoMenu.changeMenuState(demoMenu.isOpened);
      let toggleHint = getCurrentToggleHint(currentMenuState);
      
      demoMenu.changeToggleHint(
        toggleHint, 
        demoMenu.menuRootNode.querySelector(`.${menuClassesNames.toggleHintClass}`)
      );
      demoMenu.menuRootNode.classList.toggle(`${menuClassesNames.activeClass}`);
      
      return currentMenuState;  
  }
  
  jsMenuNode.querySelector(`.${menuClassesNames.toggleClass}`).addEventListener('click', toggleMenu);
})();
</script>