config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    devise_scope :user do
      authenticated :user do
        root :to => "categories#index", as: :authenticated_root
        get '/users/sign_out' => 'devise/sessions#destroy'
      end
      unauthenticated :user do
        root :to => "splashs#index", as: :unauthenticated_root
      end
    end

    resources :categories, only: [:index, :show, :new, :create]
    resources :deals, only: [:index, :show, :new, :create]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :deals, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: :create

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.includes(:deals).find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(categories_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon)
  end
end

app/views/categories/index.html.erb
<%= render 'shared/header', title: 'CATEGORIES', image1: '', image2: 'search.png', image3: '' %>
<%= render 'shared/mobile_menu', user: current_user %>
<%= render 'shared/flash'%>
<div class="holder">
  <div class="cat-card" >
  <%= render 'shared/card1', type1: 'Total Categories', type2: @categories.count, type3: '' %>
  </div>
</div>
<% if @categories.empty? %>
  <p class='empty'>No categories added yet</p>
<% else %>
  <% @categories.each do |category| %>
    <%= render 'shared/card2', category: category %>
  <% end %>
<% end %>
<div class='save-btn' >
<%= link_to 'Add New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/header', title: 'NEW CATEGORY', image1: 'back_arrow1.png', image2: 'search.png', image3: '' %>

<div class="form-group">
  <%= form_with model: @category, method: :post, local: true do |f| %>
    <div class="field">
      <%= f.text_field :name, required: true, placeholder: "Category Name" %>
    </div>
    <div class="field">
      <%= f.text_field :icon, required: true, placeholder: "Category Icon (please make sure that it is a valid image address)"%>
    </div>  
    <div class="actions">
      <%= f.submit "Save" %>
    </div>
  <% end %>
</div> 

app/views/categories/show.html.erb
<%= render 'shared/header', title: 'SINGLE CATEGORY', image1: '', image3: 'back_arrow1.png', image2: 'search.png' %>
<div class="card-1" >

  <%= render 'shared/card1', type1: 'Total Transactions', type2: Deal.sum_amounts(@category.deals), type3: '$' %>
</div>
<%= render 'shared/flash'%>
<% if @category.deals.empty? %>
  <p class='empty'>No transactions for this category yet</p>
<% else %>
  <% @category.deals.each do |deal| %>
    <%= render 'shared/card3', deal: deal %>
  <% end %>
<% end %>
<div class='save-btn' >
  <%= link_to 'Add New Transaction', new_deal_path %>
</div>